create table users (
                       id bigint generated by default as identity,
                       algorithm varchar(255),
                       password varchar(255),
                       username varchar(255),
                       primary key (id)
);

create table authority (
                           id bigint generated by default as identity,
                           name varchar(255),
                           user_id bigint,
                           primary key (id)
);

create table product (
                         id bigint generated by default as identity,
                         currency varchar(255),
                         name varchar(255),
                         price double not null,
                         primary key (id)
);

insert into users(id, username, password, algorithm) values(1, 'john', '$2a$10$xn3LI/AjqicFYZFruSwve.681477XaVNaUQbr1gioaWPn4t1KsnmG', 'BCRYPT');
insert into authority(id, name, user_id) values(1, 'READ', 1);
insert into authority(id, name, user_id) values(2, 'WRITE', 1);
insert into product(id, name, price, currency) values ( 1, 'Chocolate', 10, 'USD' );
